# Generated by Django 3.1.4 on 2021-01-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='core.Review'),
        ),
    ]
