# Generated by Django 3.1.4 on 2021-01-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210102_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
