# Generated by Django 3.1.4 on 2021-01-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_coupon_in_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_selected',
            field=models.BooleanField(default=True),
        ),
    ]
