# Generated by Django 3.1.4 on 2021-01-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_orderitem_is_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='in_use',
        ),
        migrations.AddField(
            model_name='order',
            name='use_coupon',
            field=models.BooleanField(default=False),
        ),
    ]
