# Generated by Django 3.1.1 on 2020-11-28 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20201126_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageviewsanalytics',
            options={'verbose_name_plural': 'Page Views Analytics'},
        ),
    ]
